---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: maestro
  name: maestro-terraform-runner-dataw
  labels:
    app: maestro-terraform-runner
    compontent: server
spec:
  accessModes:
  - ReadWriteOnce
  resources: 
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: maestro
  name: maestro-terraform-runner
  labels:
    app: maestro-terraform-runner
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maestro-terraform-runner
      component: server
  template:
    metadata:
      labels:
        app: maestro-terraform-runner
        component: server
    spec:
      containers:
      - name: maestro-terraform-runner
        image: harbor.coretech.chst.io/automation/maestro-terraform-runner:0.0.10
        ports:
        - containerPort: 3030
        volumeMounts:
        - mountPath: /home/node/data
          name: maestro-terraform-runner-data
      securityContext:
        fsGroup: 1000
      volumes:
      - name: maestro-terraform-runner-data
        persistentVolumeClaim:
          claimName: maestro-terraform-runner-data
      restartPolicy: Always
      imagePullSecrets:
      - name: azureregcred       

---
apiVersion: v1
kind: Service
metadata:
  namespace: maestro
  name: maestro-terraform-runner
  labels:
    app: maestro-terraform-runner
    component: server
spec:
  ports:
  - name: maestro-terraform-runner
    port: 3030
    targetPort: 3030
  selector:
    app: maestro-terraform-runner
    component: server
  type: ClusterIP

# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   namespace: maestro
#   name: maestro-terraform-runner
#   labels:
#     app: maestro-terraform-runner
#     component: server
#   annotations:
#     kubernetes.io/ingress.class: kong
#     cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   tls:
#     - hosts:
#       - maestro-terraform-runner.coretech.chst.io
#       secretName: maestro-terraform-runner-tls
#   rules:
#   - host: maestro-terraform-runner.coretech.chst.io
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: maestro-terraform-runner
#           servicePort: 3030
