sudo: false

language: node_js
node_js:
  # - "4"
  # - "5"
  # - "6"
  - "7"
cache:
  directories:
  - $HOME/.npm

before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
  - npm run check-coverage
after_success:
  - npm run report-coverage
  # - npm run semantic-release